# Generated by Django 5.2.14 on 2026-05-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='email_alerts',
            field=models.BooleanField(default=False),
        ),
    ]
