# Generated by Django 5.0.8 on 2026-05-29 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_monitor_body_monitor_headers_monitor_http_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='assert_keyword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='assert_max_response_time_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitorlog',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitorlog',
            name='region',
            field=models.CharField(blank=True, default='us-east', max_length=50),
        ),
        migrations.AddField(
            model_name='monitorlog',
            name='ssl_days_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitorlog',
            name='ssl_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitorlog',
            name='ssl_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitorlog',
            name='status',
            field=models.CharField(default='up', max_length=20),
        ),
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_windows', to='monitoring.monitor')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
