# Generated by Django 5.0.8 on 2026-05-31 08:15

import django.db.models.deletion
import monitoring.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_monitor_assert_keyword_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('environment', models.CharField(default='production', max_length=100)),
                ('api_key', models.CharField(db_index=True, default=monitoring.models.generate_api_key, max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apm_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiMetricSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=512)),
                ('requests_count', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0)),
                ('p95_latency', models.FloatField(default=0)),
                ('p99_latency', models.FloatField(default=0)),
                ('error_rate', models.FloatField(default=0)),
                ('minute_bucket', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_metric_summaries', to='monitoring.application')),
            ],
            options={
                'ordering': ['-minute_bucket'],
            },
        ),
        migrations.CreateModel(
            name='ApiMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=512)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('response_time_ms', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_metrics', to='monitoring.application')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'environment'], name='monitoring__user_id_5ad287_idx'),
        ),
        migrations.AddIndex(
            model_name='apimetricsummary',
            index=models.Index(fields=['application', 'minute_bucket'], name='monitoring__applica_cd6de7_idx'),
        ),
        migrations.AddIndex(
            model_name='apimetricsummary',
            index=models.Index(fields=['application', 'endpoint', 'minute_bucket'], name='monitoring__applica_7cf1a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='apimetricsummary',
            constraint=models.UniqueConstraint(fields=('application', 'endpoint', 'minute_bucket'), name='unique_apm_summary_per_endpoint_minute'),
        ),
        migrations.AddIndex(
            model_name='apimetric',
            index=models.Index(fields=['application', 'timestamp'], name='monitoring__applica_614fff_idx'),
        ),
        migrations.AddIndex(
            model_name='apimetric',
            index=models.Index(fields=['application', 'endpoint', 'timestamp'], name='monitoring__applica_5126e0_idx'),
        ),
        migrations.AddIndex(
            model_name='apimetric',
            index=models.Index(fields=['application', 'status_code', 'timestamp'], name='monitoring__applica_a11621_idx'),
        ),
    ]
