# Generated by Django 5.0.8 on 2026-06-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_apimetric_error_message'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='monitorlog',
            index=models.Index(fields=['monitor', 'checked_at'], name='monitoring__monitor_da6758_idx'),
        ),
        migrations.AddIndex(
            model_name='monitorlog',
            index=models.Index(fields=['checked_at'], name='monitoring__checked_afd6dd_idx'),
        ),
    ]
