# Generated by Django 5.0.8 on 2026-08-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_add_monitorlog_checked_at_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['monitor', '-started_at'], name='monitoring__monitor_db69c3_idx'),
        ),
    ]
